//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceConsumer.LdapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LdapServiceReference.ILdapConnectionService")]
    public interface ILdapConnectionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapConnectionService/ValidateUser", ReplyAction="http://tempuri.org/ILdapConnectionService/ValidateUserResponse")]
        bool ValidateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapConnectionService/ValidateUser", ReplyAction="http://tempuri.org/ILdapConnectionService/ValidateUserResponse")]
        System.Threading.Tasks.Task<bool> ValidateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapConnectionService/IsMemberOf", ReplyAction="http://tempuri.org/ILdapConnectionService/IsMemberOfResponse")]
        bool IsMemberOf(string username, string password, string cn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILdapConnectionService/IsMemberOf", ReplyAction="http://tempuri.org/ILdapConnectionService/IsMemberOfResponse")]
        System.Threading.Tasks.Task<bool> IsMemberOfAsync(string username, string password, string cn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILdapConnectionServiceChannel : WcfServiceConsumer.LdapServiceReference.ILdapConnectionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LdapConnectionServiceClient : System.ServiceModel.ClientBase<WcfServiceConsumer.LdapServiceReference.ILdapConnectionService>, WcfServiceConsumer.LdapServiceReference.ILdapConnectionService {
        
        public LdapConnectionServiceClient() {
        }
        
        public LdapConnectionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LdapConnectionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapConnectionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapConnectionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateUser(string username, string password) {
            return base.Channel.ValidateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateUserAsync(string username, string password) {
            return base.Channel.ValidateUserAsync(username, password);
        }
        
        public bool IsMemberOf(string username, string password, string cn) {
            return base.Channel.IsMemberOf(username, password, cn);
        }
        
        public System.Threading.Tasks.Task<bool> IsMemberOfAsync(string username, string password, string cn) {
            return base.Channel.IsMemberOfAsync(username, password, cn);
        }
    }
}
